/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fr_bodyalhoha_remake_NativeManager */

#ifndef _Included_fr_bodyalhoha_remake_NativeManager
#define _Included_fr_bodyalhoha_remake_NativeManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fr_bodyalhoha_remake_NativeManager
 * Method:    remake
 * Signature: (Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_fr_bodyalhoha_remake_NativeManager_remake
  (JNIEnv *, jclass, jclass);

#ifdef __cplusplus
}
#endif
#endif
